# Generated by Django 6.0.7 on 2026-08-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='userotp',
            name='system_name',
            field=models.CharField(db_index=True, default='default', max_length=50),
        ),
        migrations.AddField(
            model_name='userotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['email', 'system_name'], name='user_otps_email_23ae13_idx'),
        ),
        migrations.AlterModelTable(
            name='userotp',
            table='user_otps',
        ),
    ]
