# Generated by Django 6.0.7 on 2026-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_userotp_status_userotp_system_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del sistema (ej: mobile_app, ecommerce)', max_length=50, unique=True)),
                ('api_key', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sistema Autorizado',
                'verbose_name_plural': 'Sistemas Autorizados',
                'db_table': 'authorized_systems',
            },
        ),
    ]
