# Generated by Django 6.0.7 on 2026-08-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_authorizedsystem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizedsystem',
            options={},
        ),
        migrations.AddField(
            model_name='userotp',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authorizedsystem',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('VERIFIED', 'Verificado'), ('EXPIRED', 'Expirado'), ('BLOCKED', 'Bloqueado')], default='PENDING', max_length=10),
        ),
    ]
