# Generated by Django 6.0.7 on 2026-08-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0004_alter_authorizedsystem_options_userotp_blocked_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('system_name', models.CharField(db_index=True, max_length=50)),
                ('otp_code', models.CharField(max_length=10)),
                ('status', models.CharField(default='GENERATED', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
