# Generated by Django 6.0.7 on 2026-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_otplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otplog',
            name='status',
            field=models.CharField(default='GENERATED', max_length=30),
        ),
    ]
